
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpwicqbhwofrofiizjtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwd2ljcWJod29mcm9maWl6anRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDE1MTMsImV4cCI6MjA1ODExNzUxM30.UcbxNBzAOPmG80ygA0IgWps44GH0bh3TR-W7fHcxgzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export type Tables = Database['public']['Tables'];
export type CourseRow = Tables['courses']['Row'];
export type FacultyRow = Tables['faculty']['Row'];
export type RoomRow = Tables['rooms']['Row'];
export type TimetableEntryRow = Tables['timetable_entries']['Row'];
